### ISSUE TITLE
Do you plan to release pretrained models?

### ISSUE THREAD

**Issue by littlesulley** [darius522/dnr-utils#1]
Some people may have trouble training models on such massive amounts of data.

**Comment by bc** [comment]
I'm also interested in learning from a pretrained model and using it for transfer learning research projects. thanks

**Comment by darius522** [comment]
My apologies for the late reply and thanks Brian for reviving this issue. We are currently looking into this and will update this issue as soon as a solution is reached. Thanks for your patience!

**Comment by darius522** [comment]
I hope this is still relevant to some of you; the code used in the paper has been released at the following: https://github.com/merlresearch/cocktail-fork-separation

The repository includes a pre-trained checkpoint, the proposed MRX model class, as well as the full training and evaluation pipelines!

**Comment by littlesulley** [comment]
Wow, that's amazing! Thanks for your great efforts!
