### ISSUE TITLE
Link in README points to V1

### ISSUE THREAD

**Issue by naba89** [darius522/dnr-utils#2]
Hi, 

The link and corresponding download command in the README (https://github.com/darius522/dnr-utils#download) points to V1 version of the dataset. 

I used that command to download the old version, and now I have to re-download V2. 
Or is there a way to just download the difference between V1 and V2?

Also, is V1 a subset of V2 or are they completely different? 
Since the number of extra files is not too large, I am thinking if I should just use V1.

**Comment by darius522** [comment]
Hi, 

Thanks for the inquiry. We tried to update most documentation when we release v2 but it looks like the README was overlooked. Apologies for that. Zenodo does warn you about the existence of a newer version though ;)

v2 is completely different from v1 in terms of its content, you would therefore have the re-download the dataset in its entirety. Depending on the nature of your project, v1 might be fine. But in most case, I would just advise people to use the most up-to-date version, if possible.

-Darius

**Comment by naba89** [comment]
Ah, I see! 

Ok, yeah, I saw this on Zenodo just a while back, but while downloading I used the command in the repository since I was downloading on a server without GUI. I should have checked more closely.

Anyways, I will download the new version.
Have a nice day 🌞
